version: '2'
services:
  elastic:
    image: elasticsearch
    ports:
      - "49200:9200"
  redis:
    image: redis
    ports:
      - "49300:6379"
  test-books-img:
    build: ./src
    command: python /app/test_books.py
    ports:
      - "49400:5000"
    depends_on:
      - elastic
  celery:
    image: celery
    build: ./src
    environment:
      - C_FORCE_ROOT=true
      - DATABASE_HOST=redis
      - BROKER_URL=redis://redis:6379
    working_dir: /app/src
    command: "celery -A test_books:celery worker"
    volumes:
      - .:/app
    depends_on:
      - redis