version: '2'
services:
  elastic:
    image: elasticsearch
    ports:
      - "9200:9200"
  redis:
    image: redis
    ports:
      - "6379:6379"
  test-books-img:
    build: ./src
    command: python -u test_books.py
    ports:
      - "5000:5000"
    depends_on:
      - elastic
  celery:
    image: celery
    working_dir: /app
    command: "celery -A src.test_books celery worker"
    volumes:
      - .:/app
    depends_on:
      - redis